name: ResetPasswordBundle CI
on: [push, pull_request]
jobs:
  build:
    name: ResetPassword
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.2', '7.3', '7.4']

    steps:
      - name: Set PHP Version
        run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php-versions }}

      - name: Disable Xdebug
        run: sudo rm /etc/php/${{ matrix.php-versions }}/cli/conf.d/20-xdebug.ini

      - name: Get PHP Version
        run: |
          ver=$(php -v | grep -oP '(?<=PHP )\d.\d')
          echo "::set-output name=version::$ver"
        id: php-ver

      - name: Using PHP Version from matrix
        run: |
          echo "Runner is not using PHP Version defined in the php-versions matrix."
          php -v
          exit 1
        if: steps.php-ver.outputs.version != matrix.php-versions

      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Validate Composer
        run: composer validate --no-check-lock

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Check src with php-cs-Fixer
        run: vendor/bin/php-cs-fixer fix --config $GITHUB_WORKSPACE/.php_cs.dist --diff --diff-format udiff --dry-run

      - name: Psalm Static Analysis
        run: vendor/bin/psalm -c $GITHUB_WORKSPACE/psalm.xml
        if: always()

      - name: Unit Tests
        run: vendor/bin/simple-phpunit -c $GITHUB_WORKSPACE/phpunit.xml.dist --testsuite unit
        if: always()

      - name: Functional Tests
        run: vendor/bin/simple-phpunit -c $GITHUB_WORKSPACE/phpunit.xml.dist --testsuite functional
        if: always()

      - name: Integration Tests
        run: vendor/bin/simple-phpunit -c $GITHUB_WORKSPACE/phpunit.xml.dist --testsuite integration
        if: always()
