name: Bundle CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  composer-validate:
    name: Validate composer.json
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Validate
        run: composer validate --no-check-lock --strict

  php-cs-fixer:
    name: Lint Bundle Source
    runs-on: ubuntu-latest

    steps:
      - name: Set PHP Version
        run: sudo update-alternatives --set php /usr/bin/php7.4
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Install PHP-CS-Fixer
        run: composer global require friendsofphp/php-cs-fixer --prefer-dist --no-progress

      - name: Enforce coding standards
        run: $HOME/.composer/vendor/bin/php-cs-fixer fix --config $GITHUB_WORKSPACE/.php_cs.dist --diff --diff-format udiff --dry-run

  psalm:
    name: Psalm Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Set PHP Version
        run: sudo update-alternatives --set php /usr/bin/php7.4

      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Analyze Source
        run: vendor/bin/psalm -c $GITHUB_WORKSPACE/psalm.xml

  stable-tests:
    name: Symfony Stable
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.2', '7.3', '7.4', '8.0']
        symfony-version: ['4.4.*', '5.2.*']

    steps:
      - name: Set PHP Version
        run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php-versions }}

#      - name: Disable Xdebug
#        run: sudo rm /etc/php/${{ matrix.php-versions }}/cli/conf.d/20-xdebug.ini

      - name: Get PHP Version
        run: |
          ver=$(php -v | grep -oP '(?<=PHP )\d.\d')
          echo "::set-output name=version::$ver"
        id: php-ver

      - name: Using PHP Version from matrix
        run: |
          echo "Runner is not using PHP Version defined in the php-versions matrix."
          php -v
          exit 1
        if: steps.php-ver.outputs.version != matrix.php-versions

      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Install Global Dependencies
        run: |
          composer global require --no-progress --no-scripts --no-plugins symfony/flex dev-main

      - name: Install dependencies
        run: |
          composer config minimum-stability stable
          composer update --prefer-dist --no-progress
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony-version }}

      - name: Unit Tests
        run: vendor/bin/simple-phpunit -c $GITHUB_WORKSPACE/phpunit.xml.dist --testsuite unit
        if: always()

      - name: Functional Tests
        run: vendor/bin/simple-phpunit -c $GITHUB_WORKSPACE/phpunit.xml.dist --testsuite functional
        if: always()

      - name: Integration Tests
        run: vendor/bin/simple-phpunit -c $GITHUB_WORKSPACE/phpunit.xml.dist --testsuite integration
        if: always()

  dev-main-tests:
    name: Symfony Main
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.2', '7.3', '7.4', '8.0']

    steps:
      - name: Set PHP Version
        run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php-versions }}

#      - name: Disable Xdebug
#        run: sudo rm /etc/php/${{ matrix.php-versions }}/cli/conf.d/20-xdebug.ini

      - name: Get PHP Version
        run: |
          ver=$(php -v | grep -oP '(?<=PHP )\d.\d')
          echo "::set-output name=version::$ver"
        id: php-ver

      - name: Using PHP Version from matrix
        run: |
          echo "Runner is not using PHP Version defined in the php-versions matrix."
          php -v
          exit 1
        if: steps.php-ver.outputs.version != matrix.php-versions

      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress

      - name: Unit Tests
        run: vendor/bin/simple-phpunit -c $GITHUB_WORKSPACE/phpunit.xml.dist --testsuite unit
        if: always()

      - name: Functional Tests
        run: vendor/bin/simple-phpunit -c $GITHUB_WORKSPACE/phpunit.xml.dist --testsuite functional
        if: always()

      - name: Integration Tests
        run: vendor/bin/simple-phpunit -c $GITHUB_WORKSPACE/phpunit.xml.dist --testsuite integration
        if: always()

  lowest-version-tests:
    name: Lowest dependencies
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.2', '7.3', '7.4', '8.0']

    steps:
      - name: Set PHP Version
        run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php-versions }}

#      - name: Disable Xdebug
#        run: sudo rm /etc/php/${{ matrix.php-versions }}/cli/conf.d/20-xdebug.ini

      - name: Get PHP Version
        run: |
          ver=$(php -v | grep -oP '(?<=PHP )\d.\d')
          echo "::set-output name=version::$ver"
        id: php-ver

      - name: Using PHP Version from matrix
        run: |
          echo "Runner is not using PHP Version defined in the php-versions matrix."
          php -v
          exit 1
        if: steps.php-ver.outputs.version != matrix.php-versions

      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Install dependencies
        run: composer update --prefer-lowest --prefer-dist --no-progress

      - name: Unit Tests
        run: vendor/bin/simple-phpunit -c $GITHUB_WORKSPACE/phpunit.xml.dist --testsuite unit
        if: always()

      - name: Functional Tests
        run: vendor/bin/simple-phpunit -c $GITHUB_WORKSPACE/phpunit.xml.dist --testsuite functional
        if: always()

      - name: Integration Tests
        run: vendor/bin/simple-phpunit -c $GITHUB_WORKSPACE/phpunit.xml.dist --testsuite integration
        if: always()
